/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tarea_5;

import static com.mycompany.tarea_5.Reg_Hombre.h1;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author andri
 */
public class Reg_Mujer extends javax.swing.JFrame {

    public static ArrayList <Mujer> m1 = new ArrayList();
    private int i,j;
    private int id = 0;
    private int error;
    private String opc;
    private String buscar;
    private String tipo = "M-";
    private int conta;
    private PrintStream destino = null;
    private DataInputStream entrada = null;
    private String archivo;
    private String dato;
    private String nombre0;
    private String paterno0;
    private String materno0;
    private int edad;
    private String edad00;
    private String facultad0;
    private String id0;
    
    /**
     * Creates new form Reg_Mujer
     */
    public Reg_Mujer() {
        initComponents();
        this.setExtendedState(Carrera.MAXIMIZED_BOTH); //Pantalla completa
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro de Asistentes Mujeres ");

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CARRERA BUAP 2025");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55)))
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 50)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Verdana", 0, 50)); // NOI18N
        jButton2.setText("Listar 1");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Verdana", 0, 50)); // NOI18N
        jButton3.setText("Listar 2");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Verdana", 0, 50)); // NOI18N
        jButton4.setText("Buscar");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Verdana", 0, 50)); // NOI18N
        jButton5.setText("Regresar");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Verdana", 0, 50)); // NOI18N
        jButton7.setText("Abrir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Verdana", 0, 50)); // NOI18N
        jButton6.setText("Salvar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Verdana", 0, 50)); // NOI18N
        jButton8.setText("Listar 3");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(68, 68, 68)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(87, 87, 87)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(64, 64, 64)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(78, 78, 78)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(97, 97, 97)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\andri\\Desktop\\Benemérita Universidad Autónoma de Puebla\\2do Semestre\\Programación Orientada a Objetos\\Proyectos\\Imagenes Tarea 4\\Modificadas\\Corredor mujer.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        jLabel5.setText("Materno:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        jLabel6.setText("Paterno:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        jLabel7.setText("Edad:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        jLabel8.setText("Facultad:");

        jTextField1.setFont(new java.awt.Font("Lucida Console", 0, 50)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Lucida Console", 0, 50)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Lucida Console", 0, 50)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Lucida Console", 0, 50)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Lucida Console", 0, 50)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jTextField2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jTextField3))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(47, 47, 47)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(jTextField5))
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //BOTÓN DE REGISTRO
        String nombre = jTextField1.getText();
        String paterno = jTextField2.getText();
        String materno = jTextField3.getText();
        String edad0 = jTextField4.getText();
        int edad = Integer.valueOf(edad0);
        String facultad = jTextField5.getText();

        int opcion = JOptionPane.showConfirmDialog(null, "¿Es correcta la siguiente información?\n"
            + "Nombre: " + nombre
            + "\nPaterno: " + paterno
            + "\nMaterno: " + materno
            + "\nEdad: " + edad
            + "\nFacultad: " + facultad
            , "CONFIRMACIÓN DE DATOS", JOptionPane.YES_NO_OPTION);

        if (opcion == 0){
            Mujer muj = new Mujer();
            muj.setNombre(nombre);
            muj.setPaterno(paterno);
            muj.setMaterno(materno);
            muj.setEdad(edad);
            muj.setFacultad(facultad);

            if (m1.isEmpty()){
                id++;
            }
            else{
                id = m1.getLast().getId() + 1;
            }

            //Preseleccionar el numero de 0's
            if (id < 10){
                tipo = "M-000"+id;
            } else if (id < 100){
                tipo = "M-00"+id;
            } else if (id < 1000){
                tipo = "M-0"+id;
            } else{
                tipo = "M-"+id;
            }
            
            muj.setId(id);
            muj.setTipo(tipo);

            m1.add(muj);

            JOptionPane.showMessageDialog(null, "Gracias por confirmar al participante " + nombre
                    + ", su número de participante es: " + tipo + "\nRegistro completado", "STATUS", JOptionPane.INFORMATION_MESSAGE);

        }
        else if (opcion == 1){
            JOptionPane.showMessageDialog(null, "DATOS INCORRECTOS. \nFavor de volver a ingresar", "STATUS", JOptionPane.WARNING_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "REGISTRO CANCELADO", "STATUS", JOptionPane.ERROR_MESSAGE);
        }

        //Limpiar entradas
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // LISTAR 1
        if (m1.isEmpty()){
            JOptionPane.showMessageDialog(null, "No hay participantes femeninos registrados", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "A continuación se mostrará la información de " + m1.size() + " participante(s)", "AVISO", JOptionPane.INFORMATION_MESSAGE);

            for (i = 0; i < m1.size(); i++){
                JOptionPane.showMessageDialog(null, "Nombre: " + m1.get(i).getNombre()
                    + "\nPaterno: " + m1.get(i).getPaterno()
                    + "\nMaterno: " + m1.get(i).getMaterno()
                    + "\nEdad: " + m1.get(i).getEdad()
                    + "\nFacultad: " + m1.get(i).getFacultad()
                    + "\nId: " + m1.get(i).getTipo() 
                    , "PARTICIPANTE " + m1.get(i).getTipo(), JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // LISTAR 2
        if (m1.isEmpty()){
            JOptionPane.showMessageDialog(null, "No hay participantes femeninos registrados", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "A continuación se mostrará la información compacta de " + m1.size() + " participante(s)", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            //Saber como quiere que los muestre
            do{
                opc = JOptionPane.showInputDialog(null, "Escriba 1 si desea mostrarlos como están registrados"
                    + "\nEscriba 2 si desea mostrarlos ordenados por apellido paterno (alfabeticamente)", "MOSTRAR", JOptionPane.QUESTION_MESSAGE );

                if(!"1".equals(opc) && !"2".equals(opc) && opc != null){
                    JOptionPane.showMessageDialog(null, "Opción Inválida, vuelva a escribir", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else if (opc == null){
                    JOptionPane.showMessageDialog(null, "OPERACIÓN CANCELADA", "AVISO", JOptionPane.WARNING_MESSAGE);
                }

            }while(!"1".equals(opc) && !"2".equals(opc) && opc != null);

            // Mostrar según sea el caso

            conta = 1;
            switch (opc){
                case "1":
                for (i = 0; i < m1.size(); i++){
                    System.out.println("Participante " + conta + ":" + m1.get(i).toString());
                    conta++;
                }
                break;
                case "2":
                //Algoritmo burbuja
                //1.- Hacer copia del arreglo original para no modificarlo
                ArrayList <Mujer> m2 = (ArrayList <Mujer>) m1.clone();
                //2.- Algoritmo burbuja
                int n = m2.size();
                for (i = 0; i < n - 1; i++) {
                    for (j = 0; j < n - i - 1; j++) {
                        String apellido1 = m2.get(j).getPaterno();
                        String apellido2 = m2.get(j + 1).getPaterno();

                        if (apellido1.compareToIgnoreCase(apellido2) > 0) {
                            // Intercambiar
                            Mujer ayuda = m2.get(j);
                            m2.set(j, m2.get(j + 1));
                            m2.set(j + 1, ayuda);
                        }
                    }
                }
                // imprimir
                for (i = 0; i < m2.size(); i++){
                    System.out.println("Participante " + conta + ":" + m2.get(i).toString());
                    conta++;
                }

                break;

                case null:
                break;
                default: JOptionPane.showMessageDialog(null, "ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // BUSCAR
        error = 0;

        if (m1.isEmpty()){
            JOptionPane.showMessageDialog(null, "No hay participantes femeninos registrados", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
            do{
                opc = JOptionPane.showInputDialog(null, "Escriba 1 si desea buscar por nombre"
                     + "\nEscriba 2 si desea buscar por apellido paterno "
                     +"\nEscriba 3 si desea buscar por apellido materno", "BUSCAR", JOptionPane.QUESTION_MESSAGE );  
                
                if(!"1".equals(opc) && !"2".equals(opc) && !"3".equals(opc) && opc != null){
                     JOptionPane.showMessageDialog(null, "Opción Inválida, vuelva a escribir", "ERROR", JOptionPane.ERROR_MESSAGE);
                 } else if (opc == null){
                     JOptionPane.showMessageDialog(null, "OPERACIÓN CANCELADA", "AVISO", JOptionPane.WARNING_MESSAGE);
                 }              
                
             }while(!"1".equals(opc) && !"2".equals(opc) && !"3".equals(opc) && opc != null);
             
             // Mostrar según sea el caso
             
            conta = 1;
            switch (opc){
                
                case "1":
                    buscar = JOptionPane.showInputDialog(null, "Ingrese el nombre del participante a buscar", "BÚSQUEDA", JOptionPane.QUESTION_MESSAGE);

                    for (i = 0; i < m1.size(); i++){
                        if (buscar.equals(m1.get(i).getNombre())){
                            JOptionPane.showMessageDialog(null, "SÍ ESTÁ REGISTRADO\n"
                                + "Nombre: " + m1.get(i).getNombre()
                                + "\nPaterno: " + m1.get(i).getPaterno()
                                + "\nMaterno: " + m1.get(i).getMaterno()
                                + "\nEdad: " + m1.get(i).getEdad()
                                + "\nFacultad: " + m1.get(i).getFacultad()
                                + "\nId: " + m1.get(i).getTipo()
                                , "PARTICIPANTE " + m1.get(i).getTipo(), JOptionPane.INFORMATION_MESSAGE);
                        }
                        else{
                            error++;
                        }
                    }
            
                break;
                case "2":
                    buscar = JOptionPane.showInputDialog(null, "Ingrese el apellido paterno del participante a buscar", "BÚSQUEDA", JOptionPane.QUESTION_MESSAGE);

                    for (i = 0; i < m1.size(); i++){
                        if (buscar.equals(m1.get(i).getPaterno())){
                            JOptionPane.showMessageDialog(null, "SÍ ESTÁ REGISTRADO\n"
                                + "Nombre: " + m1.get(i).getNombre()
                                + "\nPaterno: " + m1.get(i).getPaterno()
                                + "\nMaterno: " + m1.get(i).getMaterno()
                                + "\nEdad: " + m1.get(i).getEdad()
                                + "\nFacultad: " + m1.get(i).getFacultad()
                                + "\nId: " + m1.get(i).getTipo() 
                                , "PARTICIPANTE " + m1.get(i).getTipo(), JOptionPane.INFORMATION_MESSAGE);
                        }
                        else{
                            error++;
                        }
                    }
            
                break;
                case "3":
                    buscar = JOptionPane.showInputDialog(null, "Ingrese el apellido materno del participante a buscar", "BÚSQUEDA", JOptionPane.QUESTION_MESSAGE);

                    for (i = 0; i < m1.size(); i++){
                        if (buscar.equals(m1.get(i).getMaterno())){
                            JOptionPane.showMessageDialog(null, "SÍ ESTÁ REGISTRADO\n"
                                + "Nombre: " + m1.get(i).getNombre()
                                + "\nPaterno: " + m1.get(i).getPaterno()
                                + "\nMaterno: " + m1.get(i).getMaterno()
                                + "\nEdad: " + m1.get(i).getEdad()
                                + "\nFacultad: " + m1.get(i).getFacultad()
                                + "\nId: " + m1.get(i).getTipo() 
                                , "PARTICIPANTE " + m1.get(i).getTipo(), JOptionPane.INFORMATION_MESSAGE);
                        }
                        else{
                            error++;
                        }
                    }
            
                break;
                default:
            }
            
            
            if (error == m1.size()){
                JOptionPane.showMessageDialog(null, "NO ESTÁ REGISTRADO", "BÚSQUEDA", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Menu_General mg1 = new Menu_General();
        mg1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // SALVAR
        archivo = JOptionPane.showInputDialog(null, "Escriba el nombre del archivo para salvar los datos", "ARCHIVO", JOptionPane.QUESTION_MESSAGE);
        try {
            destino = new PrintStream(new FileOutputStream(archivo+".txt")); // File
        }
        catch (FileNotFoundException ex) {
            System.out.println("Ocurrio un error");
        }
        conta = 1;
        for(i=0; i<m1.size();i++){
            destino.print(
                "PARTICIPANTE: " + conta
                + "\n" + m1.get(i).getNombre()
                + "\n" + m1.get(i).getPaterno()
                + "\n" + m1.get(i).getMaterno()
                + "\n" + m1.get(i).getEdad()
                + "\n" + m1.get(i).getFacultad()
                + "\n" + m1.get(i).getTipo()
                + "\n");

            conta++;
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         // ABRIR
        id=1;
        archivo = JOptionPane.showInputDialog(null, "Escriba el nombre del archivo para recuperar los datos", "ARCHIVO", JOptionPane.QUESTION_MESSAGE);
        try {
            entrada = new DataInputStream(new FileInputStream(archivo+".txt"));
            
            dato = entrada.readLine();
            while (dato != null){
            //Lectura de datos y copiado a variables
                nombre0 = entrada.readLine();
                paterno0 = entrada.readLine();
                materno0 = entrada.readLine();
                edad00 = entrada.readLine();
                facultad0 = entrada.readLine();
                id0 = entrada.readLine();
             //Se convierte la linea de edad en entero (porque si lo leía directamente como entero no me lo detectaba bien)
                edad = Integer.parseInt(edad00);
            
              //Copiado de datos a la memoria y al arraylist
                Mujer muj = new Mujer();
                muj.setNombre(nombre0);
                muj.setPaterno(paterno0);
                muj.setMaterno(materno0);
                muj.setEdad(edad);
                muj.setFacultad(facultad0);
                muj.setTipo(id0);
                muj.setId(id);
                
                m1.add(muj);

                id++;
                dato = entrada.readLine();
            }
            System.out.println("Datos copiados ...");
            entrada.close();
        }
        catch (IOException ex){
            System.out.println("ERROR ..." + ex.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Listar 3

        ArrayList <Mujer> m3 = (ArrayList <Mujer>) m1.clone();
        int n = m3.size();
        for (i = 0; i < n - 1; i++) {
            for (j = 0; j < n - i - 1; j++) {
                int edad1 = m3.get(j).getEdad();
                int edad2 = m3.get(j + 1).getEdad();

                if (edad1 > edad2 ) {
                    // Intercambiar
                    Mujer ayuda = m3.get(j);
                    m3.set(j, m3.get(j + 1));
                    m3.set(j + 1, ayuda);
                }
            }
        }
        // imprimir
        conta = 1;
        for (i = 0; i < m3.size(); i++){
            System.out.println("Participante " + conta + ":" + m3.get(i).toString());
            conta++;
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reg_Mujer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reg_Mujer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reg_Mujer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reg_Mujer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reg_Mujer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
